export const GET_DEMO_START = 'GET_DEMO_START';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const GET_DEMO_FAILURE = 'GET_DEMO_FAILURE';

export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_DETAILS_START = 'GET_PRODUCT_DETAILS_START';
